---
title: "RWorksheet_Layson#4a"
author: "Gilmar M. Layson"
date: "October 14, 2024"
output: pdf_document
---

#1. 
#a.
```{r}
ShoeSize <- c(6.5, 9, 8.5, 8.5, 10.5, 7, 9.5, 9, 13, 7.5, 10.5, 8.5, 12, 10.5, 13, 11.5, 8.5, 5, 10, 6.5, 7.5, 8.5, 10.5, 8.5, 10.5, 11, 9, 13)
Height <- c(66.0,68.0,64.5,65.0,70.0,64.0,70.0,71.0,72.0,64.0,74.5,67.0,71.0,71.0,77.0,72.0,59.0,62.0,72.0,66.0,64.0,67.0,73.0,69.0,72.0,70.0,69.0,70.0)
Gender <- c("F","F","F","F","M","F","F","F","M","F","M","F","M","M","M","M","F","F","M","F","F","M","M","F","M","M","M","M")

House_Hold <- data.frame(ShoeSize, Height, Gender)
House_Hold

```
#b.
```{r}

male <- subset(House_Hold, Gender == "M")
male

```
 
```{r}
female <- subset(House_Hold, Gender == "F")
female
```

#c.
```{r}
mean(ShoeSize)
mean(Height)
```

#d.
#Shoe size and height are both characteristics of a person, they are independent of each other.  There's no direct connection between how big someone's feet are and how tall they are. 

#2.
```{r}
months <- c("March", "April", "January", "November", "January", "September", "October", "September", "November", "August", "January", "November", "November", "February", "May", "August", "July", "December", "August", "August", "September", "November", "February", "April")
factor_months_vector <- factor(months)
factor_months_vector
```
#3.
```{r}
summary(months)
summary(factor_months_vector)
```
#4.
```{r}
factor_data <- c("East", "West", "North")
freq <- c(1,4,3)

new_order_data <- factor(factor_data, levels = c("East", "West", "North"))
new_order_data

f_data <- data.frame(Direction = factor_data, Frequency = freq)
f_data
```
#5.
```{r}
import_march <- read.table("C:\\Users\\User\\OneDrive\\Desktop\\Rworksheet\\Worksheet_4\\import_march.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE)
import_march


```

#6.
```{r}
num <- as.numeric(readline(prompt = "select number from 1 to 50: "))

if (is.na(num)) {
  print("Please enter a valid number.")
} else if (num < 1 || num > 50) {
  print("The number selected is beyond the range of 1 to 50.")
} else if (num == 20) {
  print("TRUE")
} else {
  print(paste("The selected number is", num))
}
```

#7.
```{r}
pay_bills <- c(1000, 500, 200, 100, 50)
count <- 0
min_bills <- function(item_price){
  
  for(bill in pay_bills){
    if(item_price >= bill){
      count <- count + item_price %% bill
      item_price <- item_price %% bill
    }
  }
  
  cat("The minimum cash required to buy a snack:", count, "\n")
}

min_bills(1550)
```


#8.
#a.
```{r}
grades <- data.frame(
  Name = c("Annie", "Thea", "Steve", "Hanna"),
  Grade1 = c(85, 65, 75, 95),
  Grade2 = c(65, 75, 55, 75),
  Grade3 = c(85, 90, 80, 100),
  Grade4 = c(100, 90, 85, 90)
)

grades
```

#b.
```{r}
ave_grades <- apply(grades[, 2:5], 1, function(x) sum(x) / length(x))

highest_avg_index <- which.max(ave_grades)
highest_avg_student <- grades$Name[highest_avg_index]
highest_avg_grade <- ave_grades[highest_avg_index]

cat("The student with the highest average grade is", highest_avg_student, "with an average of", highest_avg_grade, ".\n", sep = " ")
```



#8c
```{r}
for (j in 2:5) {
  test_scores <- grades[, j]  
  test_average <- mean(test_scores)  
  if (test_average < 80) {
    cat("The ", names(grades)[j], " test was difficult.\n", sep = "")
  }
}
```

#8d
```{r}
for (i in 1:nrow(grades)) {
  student_grades <- grades[i, 2:5]
  highest_grade <- max(student_grades)  
  if (highest_grade > 90) {
    cat(grades$Name[i], "'s highest grade this semester is ", highest_grade, ".\n", sep = "")
  }
}
```


