---
title: "Untitled"
author: "Gilmar Layson"
date: "2024-09-27"
output: html_document
---


#Using Vectors
#1. Create a vector using : operator
#a. Sequence from -5 to 5. Write the R code and its output.
#Describe its output.
x <- -5:5
x
# output [1] -5 -4 -3 -2 -1  0  1  2  3  4  5

#b. x <- 1:7. What will be the value of x?
x <- 1:7
x
#output [1] 1 2 3 4 5 6 7

  
#2.* Create a vector using seq() function
#a. seq(1, 3, by=0.2) # specify step size
#Write the R script and its output. Describe the output.
x <- seq(1, 3, by=0.2)
x
#output [1] 1.0 1.2 1.4 1.6 1.8 2.0 2.2 2.4 2.6 2.8 3.0

#3. A factory has a census of its workers. There are 50 workers in total. The following list shows their ages: 34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27,22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 43, 53, 41, 51, 35, 24,33, 41, 53, 40, 18, 44, 38, 41, 48, 27, 39, 19, 30, 61, 54, 58, 26, 18.
ages <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27, 22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 43, 53, 41, 51, 35, 24, 33, 41, 53, 40, 18, 44, 38, 41, 48, 27, 39, 19, 30, 61, 54, 58, 26, 18)
#a. Access 3rd element, what is the value?
ages[3]
#output [1] 22
  
#b. Access 2nd and 4th element, what are the values?
ages [c(2,4)]
#output [1] 28 36
  
#c. Access all but the 4th and 12th element is not included. Write the R script and its output.
ages[-c(4, 12)]


#4. *Create a vector x <- c("first"=3, "second"=0, "third"=9). Then named the vector, names(x).

#a. Print the results. Then access x[c("first", "third")].
#Describe the output.
#We access the elements with names "first" and "third" from the vector x. The output is a vector with two elements, 3 and 9.

#b. Write the code and its output.
x <- c("first"=3, "second"=0, "third"=9)
x
x[c("first", "third")]

#5. Create a sequence x from -3:2.
#a. Modify 2nd element and change it to 0;
x[2] <- 0
x
#Describe the output.
#The ":" operator is used to create a sequence of numbers from -3 to 2. The : operator modify the 2nd element and change it to 0.
#b. Write the code and its output.
x <- -3:2
x[2] <- 0
x
#output [1] -3  0 -1  0  1  2

#6. *The following data shows the diesel fuel purchased by Mr. Cruz.

#a. Create a data frame for month, price per liter (php) and purchase-quantity (liter). Write the R scripts and its output.
# Define the data
month <- c("Jan", "Feb", "March", "Apr", "May", "June")
price_per_liter <- c(52.50, 57.25, 60.00, 65.00, 74.25, 54.00)
purchase_quantity <- c(25, 30, 40, 50, 10, 45)

# Create a data frame with descriptive column names
df <- data.frame(
  Month = month,
  Price_per_Liter = price_per_liter,
  Purchase_Quantity = purchase_quantity
)

# Print the data frame
print(df)

#b. What is the average fuel expenditure of Mr. Cruz from Jan to June? Note: Use ‘weighted.mean(liter, purchase)‘. Write the R scripts and its output.
# Calculate the expenditure for each month
expenditure <- price_per_liter * purchase_quantity

# Calculate the weighted mean
average_expenditure <- weighted.mean(price_per_liter, purchase_quantity)

# Print the average expenditure
print(average_expenditure)
#output [1] 59.2625


#7. R has actually lots of built-in datasets. For example, the rivers data “gives the lengths (in miles) of 141 “major” rivers in North America, as compiled by the US Geological Survey”.
#a. Type “rivers” in your R console.
#Create a vector data with 7 elements, containing the number of elements (length) in rivers, their sum (sum), mean (mean), median(median), variance(var), standard deviation(sd), minimum (min) and maximum (max).
data(rivers)


#b. What are the results?
#The result are the minimum, maximum, mean, and max
  
#c. Write the R scripts and its outputs.
rivers_stat <- c(length(rivers), sum(rivers), mean(rivers), median(rivers), var(rivers), sd(rivers), min(rivers), max(rivers))
rivers_stat



#8. The table below gives the 25 most powerful celebrities and their annual pay as ranked by the editions of Forbes magazine and as listed on the Forbes.com website.


#a. Create vectors according to the above table.
#Write the R scripts and its output.
PowerRanking <- c(1:25)
CelebrityName <- c("Tom Cruise", "Rolling Stones", "Ophrah Winfrey", "U2", "Tiger Woods", "Steven Spielberg", "Howard Stern", "50 Cent", "Cast of the Sopranos", "Dan Brown", "Bruce Springsteen", "Donald Trump", "Muhammad Ali", "Paul McCartney", "George Lucas", "Elton John", "David Letterman", "Phil Mickelson", "J.K Rowling", "Bradd Pitt", "Peter Jackson", "Dr. Phil McGraw", "Jay Lenon", "Celine Dion", "Kobe Bryant")
Pay <- c(67, 90, 225, 110, 90, 332, 302, 41, 52, 88, 55, 44, 55, 40, 233, 34, 40, 47, 75, 25, 39, 45, 32, 40, 31)
Forbes_Ranking <- data.frame(PowerRanking = PowerRanking,
                            CelebrityName = CelebrityName, Pay = Pay)
Forbes_Ranking
#b. Modify the power ranking and pay of J.K. Rowling.
#Change power ranking to 15 and pay to 90. Write the
#R scripts and its output.
Forbes_Ranking[Forbes_Ranking$CelebrityName == "J.K Rowling", "PowerRanking"] <- 15
Forbes_Ranking[Forbes_Ranking$CelebrityName == "J.K Rowling", "Pay"] <- 90

Forbes_Ranking
#c. Create an excel file from the table above and save it as csv file(PowerRanking). Import the csv file into the RStudio. What is the R script?
  
write.csv(Forbes_Ranking, file = "PowerRanking.csv", row.names = FALSE)
importedRanking <- read.csv("PowerRanking.csv")
importedRanking

#d. Access the rows 10 to 20 and save it as Ranks.RData.
#Write the R script and its output.
Ranking <- Forbes_Ranking[10:20, ]
save(Ranking, file = "Ranks.RData")
Ranking



#e. Describe its output.
#The result shows that it prints the names and pays of celebrities in a ranking of 10 to 20.

#9. Download the Hotels-Vienna https://tinyurl.com/Hotels-Vienna
#a. Import the excel file into your RStudio.
#What is the R script?
  Hotels_Vienna <- read_excel("Hotels-Vienna.xlsx")
  Hotels_Vienna

#b. How many dimensions does the dataset have?
#What is the R script? What is its output?
DIMEN <- dim(Hotels_Vienna)
DIMEN
#c. Select columns country, neighbourhood, price, stars, accomodation_type, and ratings. Write the R script.
selectedcolumns <- Hotels_Vienna[, c("country", "neighbourhood", "price", "stars", "accommodation_type",     "rating")]
print(head(selectedcolumns))



#d. Save the data as **new.RData to your RStudio. Write the
#R script.
save(selectedcolumns, file = "new.RData")
selectedcolumns


#e. Display the first six rows and last six rows of the new.RData. What is the R script?
load("new.RData")
head(selectedcolumns)
tail(selectedcolumns)

#10. Create a list of ten (10) vegetables you ate during your lifetime. If none, just list down.
#a. Write the R scripts and its output.
vegetables <- list ("Eggplant", "Garlic", "Onion", "Beans", "Potato", "Broccoli", "Ginger", "Lettuce", "Squash", "Carrots" )
vegetables


#b. Add 2 additional vegetables after the last vegetables in the list. What is the R script and its output?
vegetables <- append(vegetables, list("Mushroom", "Okra"))
vegetables


#c. Add 4 additional vegetables after index 5. How many data points does your vegetable list have? What is the
#R script and its output?
vegetables <- append(vegetables, list("Bitter Gourd", "Bell Pepper", "Cucumber", "Chayote"))
vegetables
length(vegetables)
#16 data points in vegetables list.
  


#d. Remove the vegetables in index 5, 10, and 15. How many vegetables were left? Write the codes and its output.
vegetables <- vegetables[-c(5, 10, 15)]
vegetables

#13 vegetables left


